services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    branch: main
    envVars:
      - key: TELEGRAM_API_TOKEN
        value: "your_telegram_bot_token"
      - key: RENDER_URL
        value: "your_render_service_url"
